'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Globe,
    Search,
    TrendingUp,
    BarChart3,
    CheckCircle2,
    AlertTriangle,
    XCircle,
    ExternalLink,
    RefreshCw,
    Settings,
    FileText,
    Image,
    Link2,
    Smartphone,
    Zap,
    Eye,
    Edit2,
    MapPin,
    Star,
    ChevronRight,
    Clock,
    X
} from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { SEOScore, PageSEO } from '@/types';

// ============================================
// MOCK DATA
// ============================================

const MOCK_OVERALL_SCORE = 78;

const MOCK_PAGES: PageSEO[] = [
    {
        id: '1',
        pagePath: '/',
        pageType: 'home',
        meta: {
            title: 'Restaurant Le Gourmet | Cuisine française à Paris',
            titleAutoGenerated: false,
            description: 'Découvrez Le Gourmet, restaurant gastronomique au cœur de Paris. Cuisine française raffinée, produits de saison et ambiance élégante.',
            descriptionAutoGenerated: false,
            keywords: ['restaurant paris', 'gastronomique', 'cuisine française'],
            robots: { index: true, follow: true },
            canonicalUrl: 'https://legourmet.fr'
        },
        openGraph: {
            title: 'Restaurant Le Gourmet - Paris',
            description: 'Cuisine française raffinée au cœur de Paris',
            image: '/images/og-home.jpg',
            type: 'website'
        },
        score: {
            overall: 92,
            breakdown: {
                titleLength: 'good',
                descriptionLength: 'good',
                hasH1: true,
                hasImageAlt: true,
                hasStructuredData: true,
                mobileFriendly: true,
                pageSpeed: 89
            },
            issues: [],
            recommendations: ['Ajouter plus de mots-clés longue traîne']
        },
        lastAnalyzed: '2026-01-10T08:00:00Z',
        lastUpdated: '2026-01-08T14:00:00Z'
    },
    {
        id: '2',
        pagePath: '/menu',
        pageType: 'menu',
        meta: {
            title: 'Notre Carte | Restaurant Le Gourmet',
            titleAutoGenerated: true,
            description: 'Consultez notre carte et nos menus. Entrées, plats, desserts et vins sélectionnés avec soin.',
            descriptionAutoGenerated: true,
            keywords: ['carte restaurant', 'menu', 'plats'],
            robots: { index: true, follow: true },
            canonicalUrl: 'https://legourmet.fr/menu'
        },
        openGraph: {
            type: 'website'
        },
        score: {
            overall: 68,
            breakdown: {
                titleLength: 'warning',
                descriptionLength: 'good',
                hasH1: true,
                hasImageAlt: false,
                hasStructuredData: true,
                mobileFriendly: true,
                pageSpeed: 72
            },
            issues: ['Images sans attribut alt', 'Titre trop court'],
            recommendations: [
                'Ajouter des descriptions à toutes les images',
                'Enrichir le titre avec des mots-clés'
            ]
        },
        lastAnalyzed: '2026-01-10T08:00:00Z',
        lastUpdated: '2026-01-05T10:00:00Z'
    },
    {
        id: '3',
        pagePath: '/reservations',
        pageType: 'reservations',
        meta: {
            title: 'Réserver une table | Le Gourmet Paris',
            titleAutoGenerated: true,
            description: 'Réservez votre table en ligne au restaurant Le Gourmet. Disponibilité en temps réel.',
            descriptionAutoGenerated: true,
            keywords: ['réservation', 'table', 'en ligne'],
            robots: { index: true, follow: true },
            canonicalUrl: 'https://legourmet.fr/reservations'
        },
        openGraph: {
            type: 'website'
        },
        score: {
            overall: 85,
            breakdown: {
                titleLength: 'good',
                descriptionLength: 'warning',
                hasH1: true,
                hasImageAlt: true,
                hasStructuredData: true,
                mobileFriendly: true,
                pageSpeed: 94
            },
            issues: ['Description un peu courte'],
            recommendations: ['Enrichir la meta description avec plus de détails']
        },
        lastAnalyzed: '2026-01-10T08:00:00Z',
        lastUpdated: '2026-01-09T16:00:00Z'
    }
];

const MOCK_GOOGLE_PROFILE = {
    linked: true,
    name: 'Restaurant Le Gourmet',
    rating: 4.6,
    reviewCount: 234,
    lastSync: '2026-01-10T06:00:00Z',
    status: 'verified'
};

const MOCK_ANALYTICS = {
    impressions: 12450,
    clicks: 892,
    ctr: 7.2,
    avgPosition: 8.4,
    topKeywords: [
        { keyword: 'restaurant gastronomique paris', clicks: 156, position: 3.2 },
        { keyword: 'cuisine française paris', clicks: 98, position: 5.1 },
        { keyword: 'le gourmet paris', clicks: 234, position: 1.2 },
        { keyword: 'restaurant centre paris', clicks: 67, position: 12.4 }
    ]
};

// ============================================
// COMPONENTS (Cinematic Premium Utility Style)
// ============================================

function ScoreGauge({ score, size = 160 }: { score: number; size?: number }) {
    const radius = (size - 24) / 2;
    const circumference = 2 * Math.PI * radius;
    const progress = (score / 100) * circumference;

    const getColor = (value: number) => {
        if (value >= 80) return '#00D9A6';
        if (value >= 60) return '#f59e0b';
        return '#ef4444';
    };

    const getLabel = (value: number) => {
        if (value >= 80) return 'Excellent';
        if (value >= 60) return 'Bon, peut être amélioré';
        return 'À améliorer';
    };

    return (
        <div className="relative flex flex-col items-center" style={{ width: size }}>
            <svg width={size} height={size} className="transform -rotate-90">
                <circle
                    cx={size / 2}
                    cy={size / 2}
                    r={radius}
                    fill="none"
                    stroke="currentColor"
                    className="text-border"
                    strokeWidth="12"
                />
                <motion.circle
                    cx={size / 2}
                    cy={size / 2}
                    r={radius}
                    fill="none"
                    stroke={getColor(score)}
                    strokeWidth="12"
                    strokeLinecap="round"
                    strokeDasharray={circumference}
                    initial={{ strokeDashoffset: circumference }}
                    animate={{ strokeDashoffset: circumference - progress }}
                    transition={{ duration: 1.5, ease: 'easeOut' }}
                />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className="text-5xl font-serif italic font-black text-text-primary">{score}</span>
                <span className="text-[10px] font-black uppercase tracking-widest text-text-muted mt-1">/100</span>
            </div>
        </div>
    );
}

function StatCard({
    label,
    value,
    icon: Icon,
    change
}: {
    label: string;
    value: string | number;
    icon: React.ElementType;
    change?: { value: number; isPositive: boolean };
}) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-6 rounded-[2rem] bg-bg-secondary border border-border group hover:shadow-lg transition-all"
        >
            <div className="flex items-start justify-between mb-4">
                <p className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">{label}</p>
                <div className="w-10 h-10 rounded-xl bg-bg-tertiary flex items-center justify-center text-text-muted group-hover:bg-[#00D9A6]/10 group-hover:text-[#00D9A6] transition-all">
                    <Icon className="w-5 h-5" />
                </div>
            </div>
            <p className="text-4xl font-serif italic font-black text-text-primary">{value}</p>
            {change && (
                <p className={cn(
                    "text-[10px] font-bold uppercase tracking-widest mt-2",
                    change.isPositive ? 'text-[#00D9A6]' : 'text-rose-500'
                )}>
                    {change.isPositive ? '↑' : '↓'} {Math.abs(change.value)}% vs semaine dernière
                </p>
            )}
        </motion.div>
    );
}

function PageCard({ page, onEdit, id }: { page: PageSEO; onEdit: () => void; id?: string }) {
    const getScoreColor = (score: number) => {
        if (score >= 80) return 'text-[#00D9A6]';
        if (score >= 60) return 'text-amber-500';
        return 'text-rose-500';
    };

    const getScoreBg = (score: number) => {
        if (score >= 80) return 'bg-[#00D9A6]/10 border-[#00D9A6]/30';
        if (score >= 60) return 'bg-amber-500/10 border-amber-500/30';
        return 'bg-rose-500/10 border-rose-500/30';
    };

    const pageTypeLabels: Record<string, string> = {
        home: 'Accueil',
        menu: 'Menu',
        reservations: 'Réservations',
        contact: 'Contact',
        blog_post: 'Article',
        event: 'Événement',
        custom: 'Personnalisée'
    };

    return (
        <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="p-6 rounded-[2rem] bg-bg-secondary border border-border hover:border-text-muted/30 hover:shadow-lg transition-all group"
        >
            <div className="flex items-start justify-between">
                <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-3">
                        <span className="text-[9px] font-black uppercase tracking-[0.2em] px-3 py-1.5 rounded-lg bg-bg-tertiary text-text-muted border border-border">
                            {pageTypeLabels[page.pageType]}
                        </span>
                        <code className="text-[11px] font-mono text-[#00D9A6] bg-[#00D9A6]/5 px-2 py-1 rounded-lg">{page.pagePath}</code>
                    </div>
                    <h3 className="text-lg font-serif italic font-black text-text-primary mb-2">{page.meta.title}</h3>
                    <p className="text-sm text-text-muted leading-relaxed line-clamp-2">{page.meta.description}</p>

                    {page.score.issues.length > 0 && (
                        <div className="mt-4 flex items-center gap-2 flex-wrap">
                            {page.score.issues.slice(0, 2).map((issue, i) => (
                                <span key={i} className="text-[9px] font-bold uppercase tracking-widest px-3 py-1.5 rounded-lg bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">
                                    {issue}
                                </span>
                            ))}
                            {page.score.issues.length > 2 && (
                                <span className="text-[10px] text-text-muted font-bold">+{page.score.issues.length - 2}</span>
                            )}
                        </div>
                    )}
                </div>

                <div className="flex flex-col items-end gap-3 ml-6">
                    <div className={cn("text-2xl font-serif italic font-black px-4 py-2 rounded-xl border", getScoreColor(page.score.overall), getScoreBg(page.score.overall))}>
                        {page.score.overall}
                    </div>
                    <button
                        onClick={onEdit}
                        className="p-3 rounded-xl bg-bg-tertiary text-text-muted hover:bg-[#00D9A6]/10 hover:text-[#00D9A6] transition-all opacity-0 group-hover:opacity-100"
                    >
                        <Edit2 className="w-4 h-4" />
                    </button>
                </div>
            </div>
        </motion.div>
    );
}

function GoogleProfileCard() {
    const profile = MOCK_GOOGLE_PROFILE;

    return (
        <div className="p-6 rounded-[2rem] bg-bg-secondary border border-border">
            <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center">
                        <MapPin className="w-5 h-5 text-blue-500" />
                    </div>
                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">Google Business Profile</h3>
                </div>
                <span className="px-3 py-1.5 rounded-lg text-[9px] font-black uppercase tracking-widest bg-[#00D9A6]/10 text-[#00D9A6] border border-[#00D9A6]/20">
                    Vérifié
                </span>
            </div>

            <div className="space-y-4">
                <div className="flex items-center justify-between py-3 border-b border-border">
                    <span className="text-[10px] font-black uppercase tracking-widest text-text-muted">Établissement</span>
                    <span className="text-sm font-bold text-text-primary">{profile.name}</span>
                </div>
                <div className="flex items-center justify-between py-3 border-b border-border">
                    <span className="text-[10px] font-black uppercase tracking-widest text-text-muted">Note moyenne</span>
                    <div className="flex items-center gap-2">
                        <Star className="w-4 h-4 text-amber-500 fill-amber-500" />
                        <span className="text-sm font-bold text-text-primary">{profile.rating}</span>
                        <span className="text-[10px] text-text-muted">({profile.reviewCount})</span>
                    </div>
                </div>
                <div className="flex items-center justify-between py-3">
                    <span className="text-[10px] font-black uppercase tracking-widest text-text-muted">Dernière sync</span>
                    <span className="text-sm text-text-muted">
                        {new Date(profile.lastSync).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
                    </span>
                </div>
            </div>

            <button className="w-full mt-6 h-12 rounded-xl bg-[#00D9A6] text-white hover:bg-[#00C090] transition-colors text-[10px] font-black uppercase tracking-widest flex items-center justify-center gap-3 shadow-[0_8px_24px_rgba(0,217,166,0.25)]">
                <RefreshCw className="w-4 h-4" />
                Synchroniser maintenant
            </button>
        </div>
    );
}

function KeywordsCard() {
    const keywords = MOCK_ANALYTICS.topKeywords;

    return (
        <div className="p-6 rounded-[2rem] bg-bg-secondary border border-border" id="seo-keywords-card">
            <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-purple-500/10 flex items-center justify-center">
                    <Search className="w-5 h-5 text-purple-500" />
                </div>
                <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">Mots-clés performants</h3>
            </div>

            <div className="space-y-4">
                {keywords.map((kw, i) => (
                    <div key={i} className="flex items-center justify-between py-2">
                        <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium text-text-primary truncate">{kw.keyword}</p>
                            <p className="text-[10px] text-text-muted uppercase tracking-widest">{kw.clicks} clics</p>
                        </div>
                        <div className={cn(
                            "text-sm font-black px-3 py-1 rounded-lg border",
                            kw.position <= 3 ? 'text-[#00D9A6] bg-[#00D9A6]/5 border-[#00D9A6]/20' :
                                kw.position <= 10 ? 'text-amber-500 bg-amber-500/5 border-amber-500/20' :
                                    'text-rose-500 bg-rose-500/5 border-rose-500/20'
                        )}>
                            #{kw.position.toFixed(1)}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}

// ============================================
// MAIN PAGE
// ============================================

export default function SEOPage() {
    const [activeTab, setActiveTab] = useState<'overview' | 'pages' | 'analytics' | 'settings'>('overview');

    const tabs = [
        { id: 'overview', label: 'Vue d\'ensemble', icon: BarChart3 },
        { id: 'pages', label: 'Pages', icon: FileText },
        { id: 'analytics', label: 'Analytics', icon: TrendingUp },
        { id: 'settings', label: 'Paramètres', icon: Settings }
    ];

    return (
        <div className="flex h-screen -m-4 md:-m-8 flex-col bg-bg-primary overflow-hidden relative font-sans">
            {/* Cinematic Background */}
            <div className="absolute inset-0 pointer-events-none overflow-hidden">
                <div className="absolute top-[-10%] right-[-5%] w-[40%] h-[40%] bg-[#00D9A6]/5 blur-[120px] rounded-full" />
                <div className="absolute bottom-[-10%] left-[-10%] w-[30%] h-[30%] bg-purple-500/5 blur-[100px] rounded-full" />
                <div className="absolute top-[30%] left-[20%] w-[20%] h-[20%] bg-amber-500/5 blur-[80px] rounded-full" />
            </div>

            {/* Header */}
            <div className="relative z-30 pt-10 px-12 pb-8 flex items-center justify-between border-b border-border bg-bg-primary/40 backdrop-blur-sm">
                {/* Module Identity */}
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-2xl bg-[#00D9A6]/10 border border-[#00D9A6]/20 flex items-center justify-center shrink-0">
                        <Globe className="w-6 h-6 text-[#00D9A6]" />
                    </div>
                    <div>
                        <h1 className="text-2xl font-serif italic font-black text-text-primary tracking-tight leading-none">
                            SEO & Référencement
                        </h1>
                        <p className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted mt-1">
                            Optimisez votre visibilité sur les moteurs de recherche
                        </p>
                    </div>
                </div>

                {/* Right Actions */}
                <div className="flex items-center gap-4">
                    <Button
                        className="h-12 px-8 bg-[#00D9A6] text-white hover:bg-[#00C090] rounded-2xl font-black text-[9px] uppercase tracking-widest shadow-[0_8px_24px_rgba(0,217,166,0.25)] transition-all flex items-center gap-3"
                        id="seo-analyze-button"
                    >
                        <RefreshCw className="w-4 h-4" />
                        Analyser le site
                    </Button>
                    <Link href="/dashboard">
                        <button className="w-12 h-12 rounded-2xl bg-bg-tertiary border border-border flex items-center justify-center hover:bg-bg-secondary transition-all group">
                            <X className="w-5 h-5 text-text-muted group-hover:text-text-primary" />
                        </button>
                    </Link>
                </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 overflow-hidden flex flex-col px-12 pt-8">
                {/* Tabs */}
                <div className="shrink-0 mb-8">
                    <div className="flex items-center gap-2 bg-bg-secondary/50 backdrop-blur-sm p-1.5 rounded-2xl w-fit border border-border" id="seo-tabs">
                        {tabs.map(tab => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id as any)}
                                className={cn(
                                    "px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-[0.15em] transition-all flex items-center gap-2",
                                    activeTab === tab.id
                                        ? "bg-text-primary text-bg-primary shadow-xl"
                                        : "text-text-muted hover:text-text-primary hover:bg-bg-tertiary"
                                )}
                                id={`seo-tab-${tab.id}`}
                            >
                                <tab.icon className="w-4 h-4" />
                                {tab.label}
                            </button>
                        ))}
                    </div>
                </div>

                {/* Scrollable Content */}
                <div className="flex-1 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:'none'] pb-12">
                    <AnimatePresence mode="wait">
                        {activeTab === 'overview' && (
                            <motion.div
                                key="overview"
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -10 }}
                                className="space-y-8"
                            >
                                {/* Score + Stats */}
                                <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
                                    <div className="p-8 rounded-[2.5rem] bg-bg-secondary border border-border flex flex-col items-center justify-center" id="seo-score-gauge">
                                        <p className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted mb-6">Score SEO Global</p>
                                        <ScoreGauge score={MOCK_OVERALL_SCORE} size={160} />
                                        <p className="text-sm font-bold text-amber-500 mt-6">Bon, peut être amélioré</p>
                                    </div>

                                    <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-6">
                                        <StatCard
                                            label="Impressions (7j)"
                                            value={MOCK_ANALYTICS.impressions.toLocaleString()}
                                            icon={Eye}
                                            change={{ value: 12, isPositive: true }}
                                        />
                                        <StatCard
                                            label="Clics (7j)"
                                            value={MOCK_ANALYTICS.clicks.toLocaleString()}
                                            icon={Zap}
                                            change={{ value: 8, isPositive: true }}
                                        />
                                        <StatCard
                                            label="CTR moyen"
                                            value={`${MOCK_ANALYTICS.ctr}%`}
                                            icon={TrendingUp}
                                            change={{ value: 2, isPositive: true }}
                                        />
                                    </div>
                                </div>

                                {/* Main Grid */}
                                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                                    <div className="lg:col-span-2 space-y-6">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center">
                                                <AlertTriangle className="w-5 h-5 text-amber-500" />
                                            </div>
                                            <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">Pages à optimiser</h3>
                                        </div>
                                        {MOCK_PAGES.filter(p => p.score.overall < 80).map((page, idx) => (
                                            <PageCard
                                                key={page.id}
                                                page={page}
                                                onEdit={() => { }}
                                                id={idx === 0 ? "seo-page-to-optimize-0" : undefined}
                                            />
                                        ))}
                                        {MOCK_PAGES.filter(p => p.score.overall < 80).length === 0 && (
                                            <div className="text-center py-12 text-text-muted">
                                                <CheckCircle2 className="w-12 h-12 mx-auto mb-4 text-[#00D9A6]" />
                                                <p className="font-bold">Toutes vos pages sont bien optimisées !</p>
                                            </div>
                                        )}
                                    </div>

                                    <div className="space-y-6">
                                        <GoogleProfileCard />
                                        <KeywordsCard />
                                    </div>
                                </div>
                            </motion.div>
                        )}

                        {activeTab === 'pages' && (
                            <motion.div
                                key="pages"
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -10 }}
                                className="space-y-6"
                            >
                                <div className="flex items-center gap-3 mb-6">
                                    <div className="w-10 h-10 rounded-xl bg-[#00D9A6]/10 flex items-center justify-center">
                                        <FileText className="w-5 h-5 text-[#00D9A6]" />
                                    </div>
                                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">Toutes les pages</h3>
                                </div>
                                <div className="space-y-4" id="seo-pages-list">
                                    {MOCK_PAGES.map((page, idx) => (
                                        <PageCard
                                            key={page.id}
                                            page={page}
                                            onEdit={() => { /* TODO: Open edit modal */ }}
                                            id={idx === 0 ? "seo-edit-page-0" : undefined}
                                        />
                                    ))}
                                </div>
                            </motion.div>
                        )}

                        {activeTab === 'analytics' && (
                            <motion.div
                                key="analytics"
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -10 }}
                                className="space-y-8"
                            >
                                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                                    <StatCard
                                        label="Impressions"
                                        value={MOCK_ANALYTICS.impressions.toLocaleString()}
                                        icon={Eye}
                                        change={{ value: 12, isPositive: true }}
                                    />
                                    <StatCard
                                        label="Clics"
                                        value={MOCK_ANALYTICS.clicks.toLocaleString()}
                                        icon={Zap}
                                        change={{ value: 8, isPositive: true }}
                                    />
                                    <StatCard
                                        label="CTR"
                                        value={`${MOCK_ANALYTICS.ctr}%`}
                                        icon={TrendingUp}
                                    />
                                    <StatCard
                                        label="Position moyenne"
                                        value={MOCK_ANALYTICS.avgPosition.toFixed(1)}
                                        icon={BarChart3}
                                    />
                                </div>

                                <div className="p-8 rounded-[2.5rem] bg-bg-secondary border border-border">
                                    <div className="flex items-center gap-3 mb-6">
                                        <div className="w-10 h-10 rounded-xl bg-purple-500/10 flex items-center justify-center">
                                            <Search className="w-5 h-5 text-purple-500" />
                                        </div>
                                        <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">Top mots-clés</h3>
                                    </div>
                                    <div className="overflow-x-auto">
                                        <table className="w-full">
                                            <thead>
                                                <tr className="text-left text-[10px] font-black uppercase tracking-[0.2em] text-text-muted border-b border-border">
                                                    <th className="pb-4 pr-4">Mot-clé</th>
                                                    <th className="pb-4 px-4 text-right">Clics</th>
                                                    <th className="pb-4 px-4 text-right">Position</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {MOCK_ANALYTICS.topKeywords.map((kw, i) => (
                                                    <tr key={i} className="border-b border-border/50">
                                                        <td className="py-4 pr-4 text-sm font-medium text-text-primary">{kw.keyword}</td>
                                                        <td className="py-4 px-4 text-right text-sm text-text-muted">{kw.clicks}</td>
                                                        <td className={cn(
                                                            "py-4 px-4 text-right text-sm font-bold",
                                                            kw.position <= 3 ? 'text-[#00D9A6]' :
                                                                kw.position <= 10 ? 'text-amber-500' :
                                                                    'text-rose-500'
                                                        )}>
                                                            {kw.position.toFixed(1)}
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </motion.div>
                        )}

                        {activeTab === 'settings' && (
                            <motion.div
                                key="settings"
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -10 }}
                                className="space-y-8"
                            >
                                <div className="p-8 rounded-[2.5rem] bg-bg-secondary border border-border">
                                    <div className="flex items-center gap-3 mb-6">
                                        <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center">
                                            <Link2 className="w-5 h-5 text-blue-500" />
                                        </div>
                                        <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-text-muted">Intégrations</h3>
                                    </div>
                                    <div className="space-y-4">
                                        {[
                                            { name: 'Google Search Console', desc: 'Suivi des performances de recherche', icon: Search, connected: true },
                                            { name: 'Google Analytics 4', desc: 'Analyse du trafic web', icon: BarChart3, connected: true },
                                            { name: 'Google Business Profile', desc: 'Présence locale et avis', icon: MapPin, connected: true }
                                        ].map((integration, i) => (
                                            <div key={i} className="flex items-center justify-between p-5 rounded-2xl bg-bg-tertiary border border-border hover:border-text-muted/30 transition-all">
                                                <div className="flex items-center gap-4">
                                                    <div className="w-12 h-12 rounded-xl bg-bg-secondary flex items-center justify-center">
                                                        <integration.icon className="w-5 h-5 text-text-muted" />
                                                    </div>
                                                    <div>
                                                        <p className="font-bold text-text-primary">{integration.name}</p>
                                                        <p className="text-[10px] text-text-muted uppercase tracking-widest">{integration.desc}</p>
                                                    </div>
                                                </div>
                                                <span className={cn(
                                                    "px-3 py-1.5 rounded-lg text-[9px] font-black uppercase tracking-widest border",
                                                    integration.connected
                                                        ? "bg-[#00D9A6]/10 text-[#00D9A6] border-[#00D9A6]/20"
                                                        : "bg-bg-tertiary text-text-muted border-border"
                                                )}>
                                                    {integration.connected ? 'Connecté' : 'Non configuré'}
                                                </span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>
            </div>
        </div>
    );
}
